config/routes.rb
Rails.application.routes.draw do
  resources :points_logs

  resources :reward_takeups

  resources :rewards do
    member do
	  get 'takeoffer' => 'rewards#takeoffer'
    end
  end

  resources :params

  get 'policies/setup' => 'policies#setup'	
  post 'create_multi_policies' => 'policies#create_multi_policies'  
  resources :policies

  resources :products

  devise_for :users
  resources :users

  get 'circles/join' => 'circles#join'
  post 'join_circle_submit' => 'circles#join_circle_submit'
  resources :circles
  
  resources :roles

  root to: "home#index"

end

app/models/circle.rb
class Circle < ActiveRecord::Base
end

app/models/param.rb
class Param < ActiveRecord::Base
end

app/models/points_log.rb
class PointsLog < ActiveRecord::Base
  belongs_to :circle
  has_one :policy
  belongs_to :reward_takeup
end

app/models/policy.rb
class Policy < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :product
end

app/models/reward_takeup.rb
class RewardTakeup < ActiveRecord::Base
  belongs_to :reward
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :role
  belongs_to :circle
  validates_presence_of :name
  
  before_save :assign_defaults
  
  def assign_defaults
    self.role = Role.find_by name: "Customer" if self.role.nil?
	self.circle = Circle.find_by name: "Empty Circle" if self.circle.nil?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		if Circle.find(current_user.circle_id).group_code == "Empty"
			redirect_to circles_join_path
		elsif Policy.where("user_id = ?", current_user.id).count == 0	
			redirect_to policies_setup_path
		end
		
	end

end

app/controllers/params_controller.rb
class ParamsController < ApplicationController
  before_action :set_param, only: [:show, :edit, :update, :destroy]

  # GET /params
  # GET /params.json
  def index
    @params = Param.all
  end

  # GET /params/1
  # GET /params/1.json
  def show
  end

  # GET /params/new
  def new
    @param = Param.new
  end

  # GET /params/1/edit
  def edit
  end

  # POST /params
  # POST /params.json
  def create
    @param = Param.new(param_params)

    respond_to do |format|
      if @param.save
        format.html { redirect_to @param, notice: 'Param was successfully created.' }
        format.json { render :show, status: :created, location: @param }
      else
        format.html { render :new }
        format.json { render json: @param.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /params/1
  # PATCH/PUT /params/1.json
  def update
    respond_to do |format|
      if @param.update(param_params)
        format.html { redirect_to @param, notice: 'Param was successfully updated.' }
        format.json { render :show, status: :ok, location: @param }
      else
        format.html { render :edit }
        format.json { render json: @param.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /params/1
  # DELETE /params/1.json
  def destroy
    @param.destroy
    respond_to do |format|
      format.html { redirect_to params_url, notice: 'Param was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_param
      @param = Param.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def param_params
      params.require(:param).permit(:grouping, :name, :value)
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.order(:id)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :role_id, :circle_id, :address, :phone_number, :dob)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/helpers/params_helper.rb
module ParamsHelper
end

app/helpers/points_logs_helper.rb
module PointsLogsHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reward_takeups_helper.rb
module RewardTakeupsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/params/_form.html.erb
<%= form_for(@param) do |f| %>
  <% if @param.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@param.errors.count, "error") %> prohibited this param from being saved:</h2>

      <ul>
      <% @param.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :grouping %><br>
    <%= f.text_field :grouping %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/params/edit.html.erb
<h1>Editing Param</h1>

<%= render 'form' %>

<%= link_to 'Show', @param %> |
<%= link_to 'Back', params_path %>

app/views/params/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Params Summary</h2>

<table>
  <thead>
    <tr>

      <th class="desc" width="125">Grouping</th>

      <th class="desc" width="125">Name</th>

      <th class="desc" width="125">Value</th>

	  <th colspan="3" width="165"></th>
    </tr>
  </thead>

  <tbody>
  
	<% if @params.each.count == 0 %>
		<tr>
			<td class="desc" colspan=10>No Params currently exist.</td>
		</tr>
	<% else %>
		<% @params.each do |param| %>
			<tr>
				
					<td class="desc"><%= param.grouping %></td>
				
					<td class="desc"><%= param.name %></td>
				
					<td class="desc"><%= param.value %></td>
				
				<td width="55"><%= link_to image_tag("icon_show.png"), param %></td>
				<td width="55"><%= link_to image_tag("icon_edit.png"), edit_param_path(param) %></td>
				<td width="55"><%= link_to image_tag("icon_delete.png"), param, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
	<% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Param', new_param_path %>

app/views/params/new.html.erb
<h1>New Param</h1>

<%= render 'form' %>

<%= link_to 'Back', params_path %>

app/views/params/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Grouping:</strong>
  <%= @param.grouping %>
</p>

<p>
  <strong>Name:</strong>
  <%= @param.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @param.value %>
</p>

<%= link_to 'Edit', edit_param_path(@param) %> |
<%= link_to 'Back', params_path %>

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Listing Roles</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= role.description %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @role.description %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :role_id %><br>
    <%= f.text_field :role_id %>
  </div>
  <div class="field">
    <%= f.label :circle_id %><br>
    <%= f.text_field :circle_id %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.date_select :dob %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Listing Members</h2>

<table>
  <thead>
    <tr>
      <th class="desc" width="50">Id</th>
	  <th class="desc" width="250">Name</th>     
	  <th class="desc" width="250">Circle</th>
      <th colspan="3" width="165"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>	  
        <td class="desc"><%= user.name %></td>
        <td class="desc"><%= user.circle.name %></td>
        <td width="55"><%= link_to image_tag("icon_show.png"), user %></td>
        <td width="55"><%= link_to image_tag("icon_edit.png"), edit_user_path(user) %></td>
        <td width="55"><%= link_to image_tag("icon_delete.png"), user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<p>
  <strong>Circle:</strong>
  <%= @user.circle %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @user.phone_number %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @user.dob %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>