config/routes.rb
Rails.application.routes.draw do
  resources :points_logs

  resources :reward_takeups

  resources :rewards do
    member do
	  get 'takeoffer' => 'rewards#takeoffer'
    end
  end

  resources :params

  get 'policies/setup' => 'policies#setup'	
  post 'create_multi_policies' => 'policies#create_multi_policies'  
  resources :policies

  resources :products

  devise_for :users
  resources :users

  get 'circles/join' => 'circles#join'
  post 'join_circle_submit' => 'circles#join_circle_submit'
  resources :circles
  
  resources :roles

  root to: "home#index"

end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :product
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :set_reward, only: [:show, :edit, :update, :destroy, :takeoffer]

  # GET /rewards
  # GET /rewards.json
  def index
    @discount_rewards = Reward.where("offer_type = 'Discount'").all
	@promo_rewards = Reward.where("offer_type = 'Promo'").all
  end

  # GET /rewards/1
  # GET /rewards/1.json
  def show
  end

  def takeoffer
    takeup = RewardTakeup.new
	takeup.reward_id = @reward.id
	takeup.user_id = current_user.id
	takeup.save
	
	circle = Circle.find(current_user.circle_id)
	circle.points = circle.points - @reward.points_cost
	circle.save
	
	log = PointsLog.new
	log.reward_takeup_id = takeup.id
#	log.policy_id = 1
	log.circle_id = current_user.circle_id
	log.credit = 0
	log.debit = @reward.points_cost
	log.balance = circle.points
	log.event_type = "Reward Taken"
	log.save
	
	circle = Circle.find(current_user.circle_id)
	circle.points = circle.points - @reward.points_cost
	circle.save
	
	redirect_to rewards_path, notice: 'Reward Taken!'
  end
  
  # GET /rewards/new
  def new
    @reward = Reward.new
  end

  # GET /rewards/1/edit
  def edit
  end

  # POST /rewards
  # POST /rewards.json
  def create
    @reward = Reward.new(reward_params)

    respond_to do |format|
      if @reward.save
        format.html { redirect_to @reward, notice: 'Reward was successfully created.' }
        format.json { render :show, status: :created, location: @reward }
      else
        format.html { render :new }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rewards/1
  # PATCH/PUT /rewards/1.json
  def update
    respond_to do |format|
      if @reward.update(reward_params)
        format.html { redirect_to @reward, notice: 'Reward was successfully updated.' }
        format.json { render :show, status: :ok, location: @reward }
      else
        format.html { render :edit }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rewards/1
  # DELETE /rewards/1.json
  def destroy
    @reward.destroy
    respond_to do |format|
      format.html { redirect_to rewards_url, notice: 'Reward was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reward
      @reward = Reward.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reward_params
      params.require(:reward).permit(:product_id, :offer_type, :min_circle_size, :min_circle_points, :title, :points_cost, :discount, :desc1, :desc2, :artwork_filename, :status)
    end
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= form_for(@reward) do |f| %>
  <% if @reward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
      <% @reward.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :offer_type %><br>
    <%= f.text_field :offer_type %>
  </div>
  <div class="field">
    <%= f.label :min_circle_size %><br>
    <%= f.number_field :min_circle_size %>
  </div>
  <div class="field">
    <%= f.label :min_circle_points %><br>
    <%= f.number_field :min_circle_points %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :points_cost %><br>
    <%= f.number_field :points_cost %>
  </div>
  <div class="field">
    <%= f.label :discount %><br>
    <%= f.text_field :discount %>
  </div>
  <div class="field">
    <%= f.label :desc1 %><br>
    <%= f.text_field :desc1 %>
  </div>
  <div class="field">
    <%= f.label :desc2 %><br>
    <%= f.text_field :desc2 %>
  </div>
  <div class="field">
    <%= f.label :artwork_filename %><br>
    <%= f.text_field :artwork_filename %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rewards/edit.html.erb
<h1>Editing Reward</h1>

<%= render 'form' %>

<%= link_to 'Show', @reward %> |
<%= link_to 'Back', rewards_path %>

app/views/rewards/index.html.erb
<p id="notice"><%= notice %></p>

  <h3>Discount Offers</h3>
  <table>
  <thead>
    <tr>
      <th class="desc" width="75">Product</th>
	  <th class="desc" width="250">Title</th>
      <th class="desc" width="75">Min Size</th>
      <th class="desc" width="75">Min Points</th>
      <th class="desc" width="75">Cost</th>
      <th class="desc" width="75">Discount</th>
 	  <% if Role.find(current_user.role_id).name == 'Customer' %>
	    <th width="50"></th>
	  <% else %>			
	    <th colspan="3" width="150"></th>
	  <% end %>	
    </tr>
  </thead>
  <tbody>
		<% @discount_rewards.each do |reward| %>
			<tr>
				<td class="desc"><%= reward.product.name %></td>				
				<td class="desc"><%= reward.title %></td>					
				<td class="desc"><%= reward.min_circle_size %></td>
				<td class="desc"><%= reward.min_circle_points %> pts</td>
				<td class="desc"><%= reward.points_cost %> pts</td>
				<td class="desc"><%= reward.discount %></td>
				<% if Role.find(current_user.role_id).name == 'Customer' %>
					<td width="50"><%= link_to image_tag("basket.png"), takeoffer_reward_path(reward) %></td>				
				<% else %>
					<td width="50"><%= link_to image_tag("icon_show.png"), reward %></td>
					<td width="50"><%= link_to image_tag("icon_edit.png"), edit_reward_path(reward) %></td>
					<td width="50"><%= link_to link_to image_tag("icon_delete.png"), reward, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				<% end %>
				</tr>
		<% end %>
  </tbody>
  </table>
 
  <br/>
  <h3>Promo Offers</h3>
  <table>
  <thead>
    <tr>
      <th class="desc" width="75">Product</th>
	  <th class="desc" width="250">Title</th>
      <th class="desc" width="75">Min Size</th>
      <th class="desc" width="75">Min Points</th>
      <th class="desc" width="75">Cost</th>
 	  <% if Role.find(current_user.role_id).name == 'Customer' %>
	    <th width="50"></th>
	  <% else %>			
	    <th colspan="3" width="150"></th>
	  <% end %>	
    </tr>
  </thead>
  <tbody>
		<% @promo_rewards.each do |reward| %>
			<tr>
				<td class="desc"><%= reward.product.name %></td>				
				<td class="desc"><%= reward.title %></td>					
				<td class="desc"><%= reward.min_circle_size %></td>
				<td class="desc"><%= reward.min_circle_points %> pts</td>
				<td class="desc"><%= reward.points_cost %> pts</td>
				<% if Role.find(current_user.role_id).name == 'Customer' %>
					<td width="50"><%= link_to image_tag("basket.png"), takeoffer_reward_path(reward) %></td>				
				<% else %>
					<td width="50"><%= link_to image_tag("icon_show.png"), reward %></td>
					<td width="50"><%= link_to image_tag("icon_edit.png"), edit_reward_path(reward) %></td>
					<td width="50"><%= link_to link_to image_tag("icon_delete.png"), reward, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				<% end %>
			</tr>
		<% end %>
  </tbody>
  </table>  

<br/>

<%= link_to 'New Reward', new_reward_path %>

app/views/rewards/new.html.erb
<h1>New Reward</h1>

<%= render 'form' %>

<%= link_to 'Back', rewards_path %>

app/views/rewards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @reward.product.name %>
</p>

<p>
  <strong>Offer type:</strong>
  <%= @reward.offer_type %>
</p>

<p>
  <strong>Min circle size:</strong>
  <%= @reward.min_circle_size %>
</p>

<p>
  <strong>Min circle points:</strong>
  <%= @reward.min_circle_points %>
</p>

<p>
  <strong>Title:</strong>
  <%= @reward.title %>
</p>

<p>
  <strong>Points cost:</strong>
  <%= @reward.points_cost %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @reward.discount %>
</p>

<p>
  <strong>Desc1:</strong>
  <%= @reward.desc1 %>
</p>

<p>
  <strong>Desc2:</strong>
  <%= @reward.desc2 %>
</p>

<p>
  <strong>Artwork filename:</strong>
  <%= @reward.artwork_filename %>
</p>

<p>
  <strong>Status:</strong>
  <%= @reward.status %>
</p>

<%= link_to 'Edit', edit_reward_path(@reward) %> |
<%= link_to 'Back', rewards_path %>