config/routes.rb
Rails.application.routes.draw do
  resources :points_logs

  resources :reward_takeups

  resources :rewards do
    member do
	  get 'takeoffer' => 'rewards#takeoffer'
    end
  end

  resources :params

  get 'policies/setup' => 'policies#setup'	
  post 'create_multi_policies' => 'policies#create_multi_policies'  
  resources :policies

  resources :products

  devise_for :users
  resources :users

  get 'circles/join' => 'circles#join'
  post 'join_circle_submit' => 'circles#join_circle_submit'
  resources :circles
  
  resources :roles

  root to: "home#index"

end

app/models/points_log.rb
class PointsLog < ActiveRecord::Base
  belongs_to :circle
  has_one :policy
  belongs_to :reward_takeup
end

app/controllers/points_logs_controller.rb
class PointsLogsController < ApplicationController
  before_action :set_points_log, only: [:show, :edit, :update, :destroy]

  # GET /points_logs
  # GET /points_logs.json
  def index
    @points_logs = PointsLog.all
  end

  # GET /points_logs/1
  # GET /points_logs/1.json
  def show
  end

  # GET /points_logs/new
  def new
    @points_log = PointsLog.new
  end

  # GET /points_logs/1/edit
  def edit
  end

  # POST /points_logs
  # POST /points_logs.json
  def create
    @points_log = PointsLog.new(points_log_params)

    respond_to do |format|
      if @points_log.save
        format.html { redirect_to @points_log, notice: 'Points log was successfully created.' }
        format.json { render :show, status: :created, location: @points_log }
      else
        format.html { render :new }
        format.json { render json: @points_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /points_logs/1
  # PATCH/PUT /points_logs/1.json
  def update
    respond_to do |format|
      if @points_log.update(points_log_params)
        format.html { redirect_to @points_log, notice: 'Points log was successfully updated.' }
        format.json { render :show, status: :ok, location: @points_log }
      else
        format.html { render :edit }
        format.json { render json: @points_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /points_logs/1
  # DELETE /points_logs/1.json
  def destroy
    @points_log.destroy
    respond_to do |format|
      format.html { redirect_to points_logs_url, notice: 'Points log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_points_log
      @points_log = PointsLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def points_log_params
      params.require(:points_log).permit(:circle_id, :policy_id, :reward_takeup_id, :event_type, :debit, :credit, :balance)
    end
end

app/helpers/points_logs_helper.rb
module PointsLogsHelper
end

app/views/points_logs/_form.html.erb
<%= form_for(@points_log) do |f| %>
  <% if @points_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@points_log.errors.count, "error") %> prohibited this points_log from being saved:</h2>

      <ul>
      <% @points_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :circle_id %><br>
    <%= f.text_field :circle_id %>
  </div>
  <div class="field">
    <%= f.label :policy_id %><br>
    <%= f.text_field :policy_id %>
  </div>
  <div class="field">
    <%= f.label :reward_takeup_id %><br>
    <%= f.text_field :reward_takeup_id %>
  </div>
  <div class="field">
    <%= f.label :event_type %><br>
    <%= f.text_field :event_type %>
  </div>
  <div class="field">
    <%= f.label :debit %><br>
    <%= f.number_field :debit %>
  </div>
  <div class="field">
    <%= f.label :credit %><br>
    <%= f.number_field :credit %>
  </div>
  <div class="field">
    <%= f.label :balance %><br>
    <%= f.number_field :balance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/points_logs/edit.html.erb
<h1>Editing Points Log</h1>

<%= render 'form' %>

<%= link_to 'Show', @points_log %> |
<%= link_to 'Back', points_logs_path %>

app/views/points_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Points Logs Summary</h2>

<table>
  <thead>
    <tr>
      <th class="desc" width="150">Circle</th>
      <th class="desc" width="150">Reward</th>
      <th class="desc" width="125">Event Type</th>
      <th class="desc" width="75">Debit</th>
      <th class="desc" width="75">Credit</th>
      <th class="desc" width="75">Balance</th>
	  <th colspan="3" width="165"></th>
    </tr>
  </thead>

  <tbody>
  
	<% if @points_logs.each.count == 0 %>
		<tr>
			<td class="desc" colspan=10>No Points Logs currently exist.</td>
		</tr>
	<% else %>
		<% @points_logs.each do |points_log| %>
			<tr>
				<td class="desc"><%= points_log.circle.name %></td>
				<td class="desc"><%= points_log.reward_takeup.reward.title %></td>
				<td class="desc"><%= points_log.event_type %></td>
				<td class="desc"><%= points_log.debit %> pts</td>
				<td class="desc"><%= points_log.credit %> pts</td>				
				<td class="desc"><%= points_log.balance %> pts</td>
				<td width="55"><%= link_to image_tag("icon_show.png"), points_log %></td>
				<td width="55"><%= link_to image_tag("icon_edit.png"), edit_points_log_path(points_log) %></td>
				<td width="55"><%= link_to link_to image_tag("icon_delete.png"), points_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
	<% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Points log', new_points_log_path %>

app/views/points_logs/new.html.erb
<h1>New Points Log</h1>

<%= render 'form' %>

<%= link_to 'Back', points_logs_path %>

app/views/points_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Circle:</strong>
  <%= @points_log.circle %>
</p>

<p>
  <strong>Policy:</strong>
  <%= @points_log.policy %>
</p>

<p>
  <strong>Reward takeup:</strong>
  <%= @points_log.reward_takeup %>
</p>

<p>
  <strong>Event type:</strong>
  <%= @points_log.event_type %>
</p>

<p>
  <strong>Debit:</strong>
  <%= @points_log.debit %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @points_log.credit %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @points_log.balance %>
</p>

<%= link_to 'Edit', edit_points_log_path(@points_log) %> |
<%= link_to 'Back', points_logs_path %>