config/routes.rb
Rails.application.routes.draw do
  resources :points_logs

  resources :reward_takeups

  resources :rewards do
    member do
	  get 'takeoffer' => 'rewards#takeoffer'
    end
  end

  resources :params

  get 'policies/setup' => 'policies#setup'	
  post 'create_multi_policies' => 'policies#create_multi_policies'  
  resources :policies

  resources :products

  devise_for :users
  resources :users

  get 'circles/join' => 'circles#join'
  post 'join_circle_submit' => 'circles#join_circle_submit'
  resources :circles
  
  resources :roles

  root to: "home#index"

end

app/models/circle.rb
class Circle < ActiveRecord::Base
end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController
  before_action :set_circle, only: [:show, :edit, :update, :destroy]

  # GET /circles
  # GET /circles.json
  def index
  	if Role.find(current_user.role_id).name == 'Customer'  
		@circles = Circle.where("id = ?",current_user.circle_id).all
	else
		@circles = Circle.all
	end	
  end

  # GET /circles/1
  # GET /circles/1.json
  def show
  end

  # GET /circles/new
  def new
    @circle = Circle.new
  end
  
  def join
    @circle = Circle.new
  end
  
  def join_circle_submit
    user = User.find(current_user.id)
	circle = Circle.where("group_code = ?", params[:group_code].to_s).first
	
	user.circle_id = circle.id
	user.save
	
	redirect_to root_path	
  end
  

  # GET /circles/1/edit
  def edit
  end

  # POST /circles
  # POST /circles.json
  def create
    @circle = Circle.new(circle_params)

    respond_to do |format|
      if @circle.save
        format.html { redirect_to @circle, notice: 'Circle was successfully created.' }
        format.json { render :show, status: :created, location: @circle }
      else
        format.html { render :new }
        format.json { render json: @circle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /circles/1
  # PATCH/PUT /circles/1.json
  def update
    respond_to do |format|
      if @circle.update(circle_params)
        format.html { redirect_to @circle, notice: 'Circle was successfully updated.' }
        format.json { render :show, status: :ok, location: @circle }
      else
        format.html { render :edit }
        format.json { render json: @circle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /circles/1
  # DELETE /circles/1.json
  def destroy
    @circle.destroy
    respond_to do |format|
      format.html { redirect_to circles_url, notice: 'Circle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_circle
      @circle = Circle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def circle_params
      params.require(:circle).permit(:name, :group_code, :points, :status)
    end
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/views/circles/_form.html.erb
<%= form_for(@circle) do |f| %>
  <% if @circle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@circle.errors.count, "error") %> prohibited this circle from being saved:</h2>

      <ul>
      <% @circle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :group_code %><br>
    <%= f.text_field :group_code %>
  </div>
  <div class="field">
    <%= f.label :points %><br>
    <%= f.number_field :points %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/circles/_form_join.html.erb
<%= form_for(@circle, url: join_circle_submit_path(@circle), html: {method: "join_circle_submit"}) do |f| %>

  <% if @circle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@circle.errors.count, "error") %> prohibited this circle from being saved:</h2>

      <ul>
      <% @circle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %> 
 
  <div class="field">
    <label for="group_code">Group Code</label><br>
    <input id="group_code" name="group_code" type="string" />
  </div>  

  <div class="actions">
    <%= f.submit "Join Circle" %>
  </div>
  
<% end %>

app/views/circles/edit.html.erb
<h1>Editing Circle</h1>

<%= render 'form' %>

<%= link_to 'Show', @circle %> |
<%= link_to 'Back', circles_path %>

app/views/circles/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Listing Circles</h2>

<table>
  <thead>
    <tr>
      <th class="desc" width="175">Name</th>
      <th class="desc" width="175">Group Code</th>
      <th width="75">Points</th>
      <th colspan="3" width="165"></th>
    </tr>
  </thead>

  <tbody>
    <% @circles.each do |circle| %>
      <tr>
        <td class="desc"><%= circle.name %></td>
        <td class="desc"><%= circle.group_code %></td>
        <td><%= circle.points %></td>
        <td width="55"><%= link_to image_tag("icon_show.png"), circle %></td>
        <td width="55"><%= link_to image_tag("icon_edit.png"), edit_circle_path(circle) %></td>
        <td width="55"><%= link_to image_tag("icon_delete.png"), circle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Circle', new_circle_path %>

app/views/circles/join.html.erb
<h1>Join Existing Circle</h1>

<%= render 'form_join' %>

<%= link_to 'Back', circles_path %>

app/views/circles/new.html.erb
<h1>New Circle</h1>

<%= render 'form' %>

<%= link_to 'Back', circles_path %>

app/views/circles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @circle.name %>
</p>

<p>
  <strong>Group code:</strong>
  <%= @circle.group_code %>
</p>

<p>
  <strong>Points:</strong>
  <%= @circle.points %>
</p>

<p>
  <strong>Status:</strong>
  <%= @circle.status %>
</p>

<%= link_to 'Edit', edit_circle_path(@circle) %> |
<%= link_to 'Back', circles_path %>